name: 2022-koslicki-ani-plots
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pandas>=1.5.1
  - seaborn>=0.12.0
  - sourmash>=4.5.0,<5
  #- lxml>=4.6.3
  - jupyterlab
  - tqdm
